### PR TITLE
Assignment 3 Review

### PR DESCRIPTION
**Pull request by sudharsan-munusami**
Hi Lenin,
Please find my submission for Assignment3. 
I have completed the points mentioned in the assignment doc except for the below two points:
1. Stacked Force Plot: Facing some error as mentioned in readme. Sorting it out.
2.  Facing Error with predicting using deployed endpoint.

I'll try to debug these tomorrow and update the file. Kindly let me know of any other changes required.
Thank you!

### CODE REVIEW

**Comment by leninkumar-sv-tiger** [comment]
@sudharsan-munusami 
Thanks. The code looks complete.

Please add in the pending changes and let me know.

**Review by leninkumar-sv-tiger — APPROVED** [review]
Thanks. Please merge

**Comment by sudharsan-munusami** [comment]
Hi Lenin,
I have sorted out both the issues.

1. Error in stacked force plot:
I found two possible reasons for this error. 
       One reason was with the shap version being used. I was using the most recent version. Changed it to version '0.25.0'.
       However, the main reason for this error is that by default the notebook is not trusted in sagemaker notebook instance. So I 
       made the notebook trusted by running the following command:
           jupyter trust '.\xgboost_inbuilt_updated.ipynb'
       Doing the above two points worked for me and made the stacked force plot visible.

2. Error with endpoint:
Initially I tried to give an numpy array as input to the predictor. So altered the code and gave the inputs in csv format for the XGBoost model built and this worked fine.


Kindly review and let me know if any changes are to be made

**Comment by sudharsan-munusami** [comment]
Sure Lenin, Thanks!

**Pull request merged**
