### PR TITLE
Assignment 2 Review

### PR DESCRIPTION
**Pull request by sudharsan-munusami**
Kindly review the assignment and let me know of any changes.
Once approved, it can be merged with "Assignment_2" branch.

### CODE REVIEW

**Review by leninkumar-sv-tiger — CHANGES_REQUESTED** [review]
https://github.com/sudharsan-munusami/HARTFORD_ASSIGNMENT_SUDSM_AWS/blob/Assignment2_review/Notebooks/inbuilt-sagemaker-model/xgboost_inbuilt_updated.ipynb

**Upload processed data to s3**
Processed data will already be placed in S3. Does it have to be uploaded seperately to S3 ?

**Review by leninkumar-sv-tiger — CHANGES_REQUESTED** [review]
Please use your local machine to trigger remote Sagemaker Jobs. 

Please don't use notebook instance for this module 2.

**Review by leninkumar-sv-tiger — CHANGES_REQUESTED** [review]
Can you please also add Real-Time-Predictor to this Module-2 assigment ?

**Comment by sudharsan-munusami** [comment]
The processed data will be stored in "csv.out" format. We'll just convert it to "csv" and save it again.

I used both local machine and sagemaker instances for the assignment. Details are given in the readme.

**Comment by leninkumar-sv-tiger** [comment]
> The processed data will be stored in "csv.out" format. We'll just convert it to "csv" and save it again.
> 
> I used both local machine and sagemaker instances for the assignment. Details are given in the readme.

That should be fine. You can keep csv.out as it is. Because it is an extra load.

You can configure input to the XGB or other algorithms, like this, 
```python
train_s3_input = TrainingInput(
    "s3://ta-sagemaker-demo/output-datasets/inbuilt-xgb-preprocess-/train_data_without_header.csv.out", 
    content_type="csv",
)
validation_s3_input = TrainingInput(
    "s3://ta-sagemaker-demo/output-datasets/inbuilt-xgb-preprocess-/test_data_without_header.csv.out", 
    content_type="csv",
)
```
That extra conversion is not needed.

**Comment by sudharsan-munusami** [comment]
Got it!

**Review by leninkumar-sv-tiger — CHANGES_REQUESTED** [review]
@sudharsan-munusami 
Real-Time endpoints can be also tested run locally.

Can you please create two notebooks, once for just local model execution (End to End) and an another for remote execution on Sagemaker Platform ?

**Comment by sudharsan-munusami** [comment]
Hi Lenin,
I have created a separate notebook for local deployment in below location:
Local_Execution/xgboost_inbuilt_updated(local_execution).ipynb

Let me know of any other changes.

**Review by leninkumar-sv-tiger — CHANGES_REQUESTED** [review]
https://github.com/sudharsan-munusami/HARTFORD_ASSIGNMENT_SUDSM_AWS/blob/Assignment2_review/Local_Execution/xgboost_inbuilt_updated(local_execution).ipynb

Doesn't have local mode execution.

Local mode executions can be done both for 
- Scikit learn fit and transform
- Endpoint hosting.

Please check that

**Comment by sudharsan-munusami** [comment]
Lenin,
I was able to fit and transform the preprocessor locally. However, I'm not able to invoke an endpoint locally.
The argument instance_type="local" during endpoint deployment is throwing an error.
It says only instance_types would be accepted.

**Comment by sudharsan-munusami** [comment]
Lenin,
As per our discussion closing the Assignment 2 review PR and committing.

Note: The local execution is working fine on Sagemaker Jupyter Notebook. However, in local machine it throws an error (wrt timeout)

**Pull request merged**
